completed practice 3
KPIcoder/kpi-node pull request #2
Opened 2023-05-19 11:35 UTC by KPIcoder

2023-05-20 16:28 UTC, nosovk commented on practice3.ts
> +type CustomValue =
эмм, костыль же, есть штатное решение

2023-05-20 16:35 UTC, nosovk commented on practice3.ts
> +      for (const key in value as CustomObject) {
as не сильно далек от any в данном случае

2023-05-20 16:35 UTC, nosovk commented on practice3.ts
> +type Func = (...args: number[]) => number;
а не с цифрами работать не будет?

2023-05-20 16:36 UTC, nosovk requested changes
fix types

2023-06-10 14:12 UTC, KPIcoder commented on practice3.ts
> +type Func = (...args: number[]) => number;
Не буде, компілятор показує помилку

2023-06-14 21:00 UTC, closed without merging